/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationStatus = { 'pending' : null } |
  { 'disbursed' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'under_review' : null };
export interface BorrowerProfile {
  'id' : string,
  'ssn' : string,
  'principal' : Principal,
  'createdAt' : Time,
  'annualIncome' : bigint,
  'fullName' : string,
  'email' : string,
  'creditScore' : bigint,
}
export interface LoanApplication {
  'id' : string,
  'status' : ApplicationStatus,
  'borrowerId' : string,
  'submittedAt' : Time,
  'productId' : [] | [string],
  'reviewedAt' : [] | [Time],
  'termMonths' : bigint,
  'requestedAmount' : bigint,
  'adminNotes' : [] | [string],
  'purpose' : string,
}
export interface LoanProduct {
  'id' : string,
  'maxAmount' : bigint,
  'minAmount' : bigint,
  'name' : string,
  'description' : string,
  'termMonths' : bigint,
  'interestRate' : number,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllApplications' : ActorMethod<[], Array<LoanApplication>>,
  'getApplicationsByBorrower' : ActorMethod<[string], Array<LoanApplication>>,
  'getBorrowerByPrincipal' : ActorMethod<[Principal], [] | [BorrowerProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLoanProducts' : ActorMethod<[], Array<LoanProduct>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerBorrower' : ActorMethod<[string, BorrowerProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitApplication' : ActorMethod<[LoanApplication], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [string, ApplicationStatus, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];