/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'disbursed' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'under_review' : IDL.Null,
});
export const Time = IDL.Int;
export const LoanApplication = IDL.Record({
  'id' : IDL.Text,
  'status' : ApplicationStatus,
  'borrowerId' : IDL.Text,
  'submittedAt' : Time,
  'productId' : IDL.Opt(IDL.Text),
  'reviewedAt' : IDL.Opt(Time),
  'termMonths' : IDL.Nat,
  'requestedAmount' : IDL.Nat,
  'adminNotes' : IDL.Opt(IDL.Text),
  'purpose' : IDL.Text,
});
export const BorrowerProfile = IDL.Record({
  'id' : IDL.Text,
  'ssn' : IDL.Text,
  'principal' : IDL.Principal,
  'createdAt' : Time,
  'annualIncome' : IDL.Nat,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'creditScore' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const LoanProduct = IDL.Record({
  'id' : IDL.Text,
  'maxAmount' : IDL.Nat,
  'minAmount' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'termMonths' : IDL.Nat,
  'interestRate' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllApplications' : IDL.Func([], [IDL.Vec(LoanApplication)], ['query']),
  'getApplicationsByBorrower' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LoanApplication)],
      ['query'],
    ),
  'getBorrowerByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BorrowerProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLoanProducts' : IDL.Func([], [IDL.Vec(LoanProduct)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerBorrower' : IDL.Func([IDL.Text, BorrowerProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitApplication' : IDL.Func([LoanApplication], [], []),
  'updateApplicationStatus' : IDL.Func(
      [IDL.Text, ApplicationStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'disbursed' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'under_review' : IDL.Null,
  });
  const Time = IDL.Int;
  const LoanApplication = IDL.Record({
    'id' : IDL.Text,
    'status' : ApplicationStatus,
    'borrowerId' : IDL.Text,
    'submittedAt' : Time,
    'productId' : IDL.Opt(IDL.Text),
    'reviewedAt' : IDL.Opt(Time),
    'termMonths' : IDL.Nat,
    'requestedAmount' : IDL.Nat,
    'adminNotes' : IDL.Opt(IDL.Text),
    'purpose' : IDL.Text,
  });
  const BorrowerProfile = IDL.Record({
    'id' : IDL.Text,
    'ssn' : IDL.Text,
    'principal' : IDL.Principal,
    'createdAt' : Time,
    'annualIncome' : IDL.Nat,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'creditScore' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const LoanProduct = IDL.Record({
    'id' : IDL.Text,
    'maxAmount' : IDL.Nat,
    'minAmount' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'termMonths' : IDL.Nat,
    'interestRate' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllApplications' : IDL.Func([], [IDL.Vec(LoanApplication)], ['query']),
    'getApplicationsByBorrower' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LoanApplication)],
        ['query'],
      ),
    'getBorrowerByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BorrowerProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLoanProducts' : IDL.Func([], [IDL.Vec(LoanProduct)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerBorrower' : IDL.Func([IDL.Text, BorrowerProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitApplication' : IDL.Func([LoanApplication], [], []),
    'updateApplicationStatus' : IDL.Func(
        [IDL.Text, ApplicationStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };